# Config file for automatic testing at travis-ci.org

language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27

cache:
  - pip
  
before_install:
  - pip install --upgrade pip

install:
  - pip install -r test_requirements.txt

script:
  - tox
